/* CVS $Id: $ */
package org.soya.consent.vocab;

import org.apache.jena.ontology.*;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from file:/Users/juang/CodeRepo/experiments/schemagen/owl/dpv-base.ttl
 *
 * @author Auto-generated by schemagen on 22 Dec 2020 06:00
 */
public class DPV {
    /**
     * <p>The namespace of the vocabulary as a string</p>
     */
    public static final String NS = "http://www.w3.org/ns/dpv#";
    /**
     * <p>The ontology's owl:versionInfo as a string</p>
     */
    public static final String VERSION_INFO = "0.1";
    /**
     * <p>The ontology model that holds the vocabulary terms</p>
     */
    private static final OntModel M_MODEL = ModelFactory.createOntologyModel(OntModelSpec.OWL_MEM, null);
    /**
     * <p>The namespace of the vocabulary as a resource</p>
     */
    public static final Resource NAMESPACE = M_MODEL.createResource(NS);
    /**
     * <p>We replicate all the properties except Legalbasis of personal data handling
     * for consent, to declare what kinds of personal data handling are consented
     * to</p>
     */
    public static final ObjectProperty HAS_DATA_CONTROLLER = M_MODEL.createObjectProperty("http://www.w3.org/ns/dpv#hasDataController");
    /**
     * <p>We replicate all the properties except Legalbasis of personal data handling
     * for consent, to declare what kinds of personal data handling are consented
     * to</p>
     */
    public static final ObjectProperty HAS_DATA_SUBJECT = M_MODEL.createObjectProperty("http://www.w3.org/ns/dpv#hasDataSubject");
    public static final ObjectProperty HAS_LEGAL_BASIS = M_MODEL.createObjectProperty("http://www.w3.org/ns/dpv#hasLegalBasis");
    /**
     * <p>We replicate all the properties except Legalbasis of personal data handling
     * for consent, to declare what kinds of personal data handling are consented
     * to</p>
     */
    public static final ObjectProperty HAS_PERSONAL_DATA_CATEGORY = M_MODEL.createObjectProperty("http://www.w3.org/ns/dpv#hasPersonalDataCategory");
    /**
     * <p>We replicate all the properties except Legalbasis of personal data handling
     * for consent, to declare what kinds of personal data handling are consented
     * to</p>
     */
    public static final ObjectProperty HAS_PROCESSING = M_MODEL.createObjectProperty("http://www.w3.org/ns/dpv#hasProcessing");
    /**
     * <p>We replicate all the properties except Legalbasis of personal data handling
     * for consent, to declare what kinds of personal data handling are consented
     * to</p>
     */
    public static final ObjectProperty HAS_PURPOSE = M_MODEL.createObjectProperty("http://www.w3.org/ns/dpv#hasPurpose");
    /**
     * <p>We replicate all the properties except Legalbasis of personal data handling
     * for consent, to declare what kinds of personal data handling are consented
     * to</p>
     */
    public static final ObjectProperty HAS_RECIPIENT = M_MODEL.createObjectProperty("http://www.w3.org/ns/dpv#hasRecipient");
    public static final ObjectProperty HAS_LOCATION = M_MODEL.createObjectProperty("http://www.w3.org/ns/dpv#hasLocation");
    /**
     * <p>Normally this would be the dataSubject, but in some exceptional cases, the
     * consent might be given on behalf by someone else, e.g. parents of minors.</p>
     */
    public static final ObjectProperty PROVISION_BY = M_MODEL.createObjectProperty("http://www.w3.org/ns/dpv#provisionBy");
    public static final ObjectProperty PROVISION_TIME = M_MODEL.createObjectProperty("http://www.w3.org/ns/dpv#provisionTime");
    /**
     * <p>Normally this would be the dataSubject, but in some exceptional cases, the
     * consent might be withdraawn on behalf by someone else, e.g. parents of minors.</p>
     */
    public static final ObjectProperty WITHDRAWAL_BY = M_MODEL.createObjectProperty("http://www.w3.org/ns/dpv#withdrawalBy");
    public static final ObjectProperty WITHDRAWAL_TIME = M_MODEL.createObjectProperty("http://www.w3.org/ns/dpv#withdrawalTime");
    public static final DatatypeProperty EXPIRY_TIME = M_MODEL.createDatatypeProperty("http://www.w3.org/ns/dpv#expiryTime");
    /**
     * <p>The actual notice that the Data Subject received to consent to, either a text
     * or link to a document, which should be usable to decide whether the form or
     * consent was compliant to legislation, e.g. documenting how the user has been
     * informed about rights and implications (such as, right to data portability,right
     * to recitffy, right to erasure, right to restrict processing, right to object,
     * rights regarding automated decision making or profiling, processors, third
     * parties, sub-processors, outside-EEA transfers, automated decision-making,
     * or other necessary details of the privacy-policy). Can be TextOrDocumentOrURI.</p>
     */
    public static final AnnotationProperty CONSENT_NOTICE = M_MODEL.createAnnotationProperty("http://www.w3.org/ns/dpv#consentNotice");
    public static final AnnotationProperty EXPIRY = M_MODEL.createAnnotationProperty("http://www.w3.org/ns/dpv#expiry");
    /**
     * <p>Can be TextOrDocumentOrURI</p>
     */
    public static final AnnotationProperty EXPIRY_CONDITION = M_MODEL.createAnnotationProperty("http://www.w3.org/ns/dpv#expiryCondition");
    /**
     * <p>This field can be used to proivde a justification why the provision was provided
     * by another DataSubject or legal entity, e.g. declariing the relationship (parent,
     * guardian), in combination with the field provisionBy</p>
     */
    public static final AnnotationProperty PROVISION_BY_JUSTIFICATION = M_MODEL.createAnnotationProperty("http://www.w3.org/ns/dpv#provisionByJustification");
    /**
     * <p>Can be used to record information of how consent was provided e.g. by a click
     * to a form, in writing, etc., by logging into a system and confirm per email,
     * or with some additional authentication, etc.</p>
     */
    public static final AnnotationProperty PROVISION_METHOD = M_MODEL.createAnnotationProperty("http://www.w3.org/ns/dpv#provisionMethod");
    /**
     * <p>This field can be used to proivde a justification why the weithdrawal was
     * done by another DataSubject or legal entity, e.g. declariing the relationship
     * (parent, guardian), in combination with the field withdrawalBy</p>
     */
    public static final AnnotationProperty WITHDRAWAL_BY_JUSTIFICATION = M_MODEL.createAnnotationProperty("http://www.w3.org/ns/dpv#withdrawalByJustification");
    /**
     * <p>Can be used to record information of how to withdraw consent, e.g. by a click
     * to a form, in writing, etc., by logging into a system and confirm per email,
     * or with some additional authentication, etc.</p>
     */
    public static final AnnotationProperty WITHDRAWAL_METHOD = M_MODEL.createAnnotationProperty("http://www.w3.org/ns/dpv#withdrawalMethod");
    public static final OntClass ACADEMIC_RESEARCH = M_MODEL.createClass("http://www.w3.org/ns/dpv#AcademicResearch");
    public static final OntClass ACCESS_CONTROL = M_MODEL.createClass("http://www.w3.org/ns/dpv#AccessControl");
    public static final OntClass ADAPT = M_MODEL.createClass("http://www.w3.org/ns/dpv#Adapt");
    public static final OntClass AGE = M_MODEL.createClass("http://www.w3.org/ns/dpv#Age");
    public static final OntClass ALIGN = M_MODEL.createClass("http://www.w3.org/ns/dpv#Align");
    public static final OntClass ANALYSE = M_MODEL.createClass("http://www.w3.org/ns/dpv#Analyse");
    public static final OntClass ANONYMISE = M_MODEL.createClass("http://www.w3.org/ns/dpv#Anonymise");
    /**
     * <p>A 'child' is distinct from a 'minor'. For example, the legal age for a 'minor'
     * in most countries is 18, whereas a 'child' can be a minor below the age of
     * 14.</p>
     */
    public static final OntClass CHILD = M_MODEL.createClass("http://www.w3.org/ns/dpv#Child");
    public static final OntClass COMBINE = M_MODEL.createClass("http://www.w3.org/ns/dpv#Combine");
    public static final OntClass COMMERCIAL_INTEREST = M_MODEL.createClass("http://www.w3.org/ns/dpv#CommercialInterest");
    public static final OntClass COMMERCIAL_RESEARCH = M_MODEL.createClass("http://www.w3.org/ns/dpv#CommercialResearch");
    public static final OntClass CONSENT = M_MODEL.createClass("http://www.w3.org/ns/dpv#Consent");
    public static final OntClass CONSULT = M_MODEL.createClass("http://www.w3.org/ns/dpv#Consult");
    public static final OntClass DATA_CONTROLLER = M_MODEL.createClass("http://www.w3.org/ns/dpv#DataController");
    public static final OntClass DATA_PROCESSOR = M_MODEL.createClass("http://www.w3.org/ns/dpv#DataProcessor");
    public static final OntClass DATA_SUBJECT = M_MODEL.createClass("http://www.w3.org/ns/dpv#DataSubject");
    public static final OntClass DEMOGRAPHIC = M_MODEL.createClass("http://www.w3.org/ns/dpv#Demographic");
    public static final OntClass DERIVE = M_MODEL.createClass("http://www.w3.org/ns/dpv#Derive");
    public static final OntClass DERIVED_PERSONAL_DATA = M_MODEL.createClass("http://www.w3.org/ns/dpv#DerivedPersonalData");
    public static final OntClass DISCLOSE = M_MODEL.createClass("http://www.w3.org/ns/dpv#Disclose");
    public static final OntClass DISCLOSE_BY_TRANSMISSION = M_MODEL.createClass("http://www.w3.org/ns/dpv#DiscloseByTransmission");
    public static final OntClass DISSEMINATE = M_MODEL.createClass("http://www.w3.org/ns/dpv#Disseminate");
    public static final OntClass EXTERNAL = M_MODEL.createClass("http://www.w3.org/ns/dpv#External");
    public static final OntClass FRAUD_PREVENTION_AND_DETECTION = M_MODEL.createClass("http://www.w3.org/ns/dpv#FraudPreventionAndDetection");
    public static final OntClass GENDER = M_MODEL.createClass("http://www.w3.org/ns/dpv#Gender");
    public static final OntClass HEALTH_RECORD = M_MODEL.createClass("http://www.w3.org/ns/dpv#HealthRecord");
    public static final OntClass IDENTITY_VERIFICATION = M_MODEL.createClass("http://www.w3.org/ns/dpv#IdentityVerification");
    public static final OntClass LEGAL_BASIS = M_MODEL.createClass("http://www.w3.org/ns/dpv#LegalBasis");
    public static final OntClass LEGAL_ENTITY = M_MODEL.createClass("http://www.w3.org/ns/dpv#LegalEntity");
    public static final OntClass MAKE_AVAILABLE = M_MODEL.createClass("http://www.w3.org/ns/dpv#MakeAvailable");
    public static final OntClass MEDICAL_HEALTH = M_MODEL.createClass("http://www.w3.org/ns/dpv#MedicalHealth");
    public static final OntClass NON_COMMERCIAL_RESEARCH = M_MODEL.createClass("http://www.w3.org/ns/dpv#NonCommercialResearch");
    /**
     * <p>Harsh: Change name to PersonalDataCategory since DataCategory can be non-personal
     * data. Axel: Ageed</p>
     */
    public static final OntClass PERSONAL_DATA_CATEGORY = M_MODEL.createClass("http://www.w3.org/ns/dpv#PersonalDataCategory");
    public static final OntClass PERSONAL_DATA_HANDLING = M_MODEL.createClass("http://www.w3.org/ns/dpv#PersonalDataHandling");
    public static final OntClass PHYSICAL_CHARACTERISTIC = M_MODEL.createClass("http://www.w3.org/ns/dpv#PhysicalCharacteristic");
    public static final OntClass PRESCRIPTION = M_MODEL.createClass("http://www.w3.org/ns/dpv#Prescription");
    public static final OntClass PROCESSING = M_MODEL.createClass("http://www.w3.org/ns/dpv#Processing");
    public static final OntClass PROFILING = M_MODEL.createClass("http://www.w3.org/ns/dpv#Profiling");
    public static final OntClass PSEUDO_ANONYMISE = M_MODEL.createClass("http://www.w3.org/ns/dpv#PseudoAnonymise");
    public static final OntClass PURPOSE = M_MODEL.createClass("http://www.w3.org/ns/dpv#Purpose");
    public static final OntClass RECIPIENT = M_MODEL.createClass("http://www.w3.org/ns/dpv#Recipient");
    public static final OntClass RESEARCH_AND_DEVELOPMENT = M_MODEL.createClass("http://www.w3.org/ns/dpv#ResearchAndDevelopment");
    public static final OntClass RESTRICT = M_MODEL.createClass("http://www.w3.org/ns/dpv#Restrict");
    public static final OntClass RETRIEVE = M_MODEL.createClass("http://www.w3.org/ns/dpv#Retrieve");
    public static final OntClass SECURITY = M_MODEL.createClass("http://www.w3.org/ns/dpv#Security");
    public static final OntClass SELL_DATA_TO_THIRD_PARTIES = M_MODEL.createClass("http://www.w3.org/ns/dpv#SellDataToThirdParties");
    public static final OntClass SELL_INSIGHTS_FROM_DATA = M_MODEL.createClass("http://www.w3.org/ns/dpv#SellInsightsFromData");
    public static final OntClass SELL_PRODUCTS_TO_DATA_SUBJECT = M_MODEL.createClass("http://www.w3.org/ns/dpv#SellProductsToDataSubject");
    public static final OntClass SELL_TARGETTED_ADVERTISEMENTS = M_MODEL.createClass("http://www.w3.org/ns/dpv#SellTargettedAdvertisements");
    public static final OntClass SERVICE_OPTIMIZATION = M_MODEL.createClass("http://www.w3.org/ns/dpv#ServiceOptimization");
    public static final OntClass SERVICE_PERSONALIZATION = M_MODEL.createClass("http://www.w3.org/ns/dpv#ServicePersonalization");
    public static final OntClass SERVICE_PROVISION = M_MODEL.createClass("http://www.w3.org/ns/dpv#ServiceProvision");
    public static final OntClass SHARE = M_MODEL.createClass("http://www.w3.org/ns/dpv#Share");
    public static final OntClass THIRD_PARTY = M_MODEL.createClass("http://www.w3.org/ns/dpv#ThirdParty");
    public static final OntClass TRANSFORM = M_MODEL.createClass("http://www.w3.org/ns/dpv#Transform");
    public static final OntClass TRANSMIT = M_MODEL.createClass("http://www.w3.org/ns/dpv#Transmit");
    public static final OntClass USE = M_MODEL.createClass("http://www.w3.org/ns/dpv#Use");

    public static final OntClass LOCATION = M_MODEL.createClass("http://www.w3.org/ns/dpv#LOCATION");

    /**
     * <p>The namespace of the vocabulary as a string</p>
     *
     * @return namespace as String
     * @see #NS
     */
    public static String getURI() {
        return NS;
    }

}
